# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-02 23:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='view_count',
        ),
    ]
