# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-02 23:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_article_view_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewArticle',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用戶觀看紀錄',
                'verbose_name_plural': '用戶觀看紀錄',
            },
        ),
        migrations.AlterUniqueTogether(
            name='viewarticle',
            unique_together=set([('user', 'article')]),
        ),
    ]
